platform :ios, '8.0'
use_frameworks!

target 'XianHui' do
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'AVOSCloudCrashReporting'
pod 'MJRefresh'
pod 'UITableView+FDTemplateLayoutCell'
pod 'SDWebImage'
pod 'Masonry'
pod 'FMDB'
pod 'CTAssetsPickerController',  '~> 3.3.0'
pod 'DZNEmptyDataSet'
pod 'TWMessageBarManager'
pod 'MWPhotoBrowser'
pod 'UITextView+Placeholder', '~> 1.2'
pod 'BKPasscodeView'

pod 'Palau', '~> 1.0'
pod 'SwiftString'
pod 'IQKeyboardManagerSwift'
pod 'ImagePickerSheetController'
pod 'RealmSwift'
pod 'Ruler', '~> 0.6'
pod 'Proposer', '~> 0.7.1'
pod 'Alamofire', '~> 3.3'
pod 'SnapKit', '~> 0.15.0'
pod 'KeyboardMan', '~> 0.6.0'
pod 'Kingfisher', '~> 2.3'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'PageMenu'
pod 'ICSPullToRefresh', '~> 0.4'
pod 'EAIntroView', '~> 2.9.0'
pod 'CryptoSwift'
pod 'Charts'
pod 'SwiftDate'
pod 'LTInfiniteScrollView-Swift'

end

